/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toDoList;

public class App {
    public String getGreeting() {
        return "Hello World";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        ToDoList toDo = new ToDoList();
        toDo.addTask();

        toDo.removeTask();

        System.out.println(toDo.getToDoList().size());

    }
}
